version: '3.7'
services:
  registry:
    container_name: registry
    restart: unless-stopped
    image: registry:2.7
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - /mnt/shetab/docker/apps/registry/volume:/var/lib/registry
      - /mnt/shetab/docker/apps/registry/data:/data
  registry-ui:
    image: jc21/registry-ui
    container_name: registry-ui
    environment:
      - REGISTRY_HOST=registry.regitstry.com
      - REGISTRY_SSL=true
      - REGISTRY_DOMAIN=registry.regitstry.com
      - REGISTRY_STORAGE_DELETE_ENABLED=1
      - REGISTRY_USER=admin
      - REGISTRY_PASS=changeit
    restart: on-failure
    links:
     - registry
  webserver:
    container_name: nginx
    image: nginx:1.21.6
    restart: unless-stopped
    volumes:
      - /mnt/shetab/docker/apps/nginx/conf.d/:/etc/nginx/conf.d/
      - /mnt/shetab/docker/apps/nginx/certs/:/etc/nginx/certs/
    ports:
      - "80:80"
      - "443:443"
    links:
     - registry
     - registry-ui