version: '3.7'
services:
  webserver:
    container_name: nginx
    image: nginx:1.21.6
    restart: unless-stopped
    volumes:
      - /mnt/docker/apps/nginx/conf.d/:/etc/nginx/conf.d/
      - /mnt/docker/apps/nginx/certs/:/etc/nginx/certs/
    ports:
      - "80:80"
      - "443:443"
networks:
  default:
    external:
      name: registry_default
